### ISSUE TITLE
Test failures for apptools.persistence on Python 3.9

### ISSUE THREAD

**Issue by kitchoi** [enthought/apptools#209]
I got the following test failures from `apptools.persistence` when I ran the test suite with Python 3.9:
```
$ python -m unittest discover -t . apptools.persistence
...s....EE..........
======================================================================
ERROR: test_pickle_classic (apptools.persistence.tests.test_state_pickler.TestDictPickler)
Test if classic classes can be pickled.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 291, in test_pickle_classic
    self.verify(t, state)
  File "/Users/kchoi/Work/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 151, in verify
    decodestring = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'

======================================================================
ERROR: test_pickle_traits (apptools.persistence.tests.test_state_pickler.TestDictPickler)
Test if traited classes can be pickled.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 365, in test_pickle_traits
    self.verify(t, state)
  File "/Users/kchoi/Work/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 151, in verify
    decodestring = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'

----------------------------------------------------------------------
Ran 20 tests in 0.015s

FAILED (errors=2, skipped=1)
```

These tests are passing on Python 3.8

**Comment by kitchoi** [comment]
`base64.decodestring` is deprecated since Python 3.1.
