### ISSUE TITLE
Tests fail when mayavi 4.7.4 (with VTK 9.1.0) is in the same environment

### ISSUE THREAD

**Issue by itziakos** [enthought/apptools#305]
```
ERROR: test_state_is_saveable (apptools.persistence.tests.test_state_pickler.TestDictPickler)
Test if the state can be saved like the object itself.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\edm-root\envs\build-env\lib\site-packages\apptools\persistence\tests\test_state_pickler.py", line 460, in test_state_is_saveable
    self.verify_state(state1, state)
  File "C:\edm-root\envs\build-env\lib\site-packages\apptools\persistence\tests\test_state_pickler.py", line 254, in verify_state
    self.assertEqual(state1._tvtk, state._tvtk)
  File "C:\edm-root\envs\build-env\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\edm-root\envs\build-env\lib\unittest\case.py", line 819, in _baseAssertEqual
    if not first == second:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by corranwebster** [comment]
Initially this looks to be an issue with TVTK or the TVTK support.
