### ISSUE TITLE
apptools.preferences does not support storing unicode values.

### ISSUE THREAD

**Issue by sjagoe** [enthought/apptools#35]
```python
Exception occurred in traits notification handler for object: <Preferences object at 0x40c19b0>, trait: last_name, old value: value, new value: TestUÜöser
Traceback (most recent call last):
  File "lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "lib/python2.7/site-packages/apptools/preferences/preferences_helper.py", line 71, in _anytrait_changed
    self.preferences.set('%s.%s' % (self._get_path(), trait_name), new)
  File "lib/python2.7/site-packages/apptools/preferences/scoped_preferences.py", line 166, in set
    node.set(path, value)
  File "lib/python2.7/site-packages/apptools/preferences/preferences.py", line 191, in set
    node.set('.'.join(components[1:]), value)
  File "lib/python2.7/site-packages/apptools/preferences/preferences.py", line 185, in set
    self._set(path, value)
  File "lib/python2.7/site-packages/apptools/preferences/preferences.py", line 546, in _set
    value = str(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-6: ordinal not in range(128)
```

**Comment by dpinte** [comment]
Fixed by #41. Closing
