### ISSUE TITLE
Test failures with PYTHONHASHSEED=random.

### ISSUE THREAD

**Issue by mdickinson** [enthought/apptools#49]
There are several (random, of course) test failures when running the test suite with PYTHONHASHSEED=random, indicating that we've got dictionary-order dependencies either in the core code (bad), or the test-suite (not so bad, but should still be fixed).  An example test run is below.

```
(Canopy 64bit) taniyama:apptools mdickinson$ PYTHONHASHSEED=random nosetests .
............................................................................................................F.............F..............F..............F.............F................F...EF.F....................F........................................................................................................................................................................
======================================================================
ERROR: Test if classic classes can be pickled.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 245, in test_pickle_classic
    self.verify(t, state)
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 112, in verify
    self.assertEqual(lst[-1]['data']['data']['a'], 'b')
TypeError: 'NoneType' object has no attribute '__getitem__'

======================================================================
FAIL: test retrieving the names of bound objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/naming/tests/context_test_case.py", line 514, in test_search
    self.assertEqual( names, ['one', 'sub/sub sub/one'] )
AssertionError: Lists differ: ['sub/sub sub/one', 'one'] != ['one', 'sub/sub sub/one']

First differing element 0:
sub/sub sub/one
one

- ['sub/sub sub/one', 'one']
+ ['one', 'sub/sub sub/one']

======================================================================
FAIL: test retrieving the names of bound objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/naming/tests/context_test_case.py", line 514, in test_search
    self.assertEqual( names, ['one', 'sub/sub sub/one'] )
AssertionError: Lists differ: ['sub/sub sub/one', 'one'] != ['one', 'sub/sub sub/one']

First differing element 0:
sub/sub sub/one
one

- ['sub/sub sub/one', 'one']
+ ['one', 'sub/sub sub/one']

======================================================================
FAIL: test retrieving the names of bound objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/naming/tests/context_test_case.py", line 514, in test_search
    self.assertEqual( names, ['one', 'sub/sub sub/one'] )
AssertionError: Lists differ: ['sub/sub sub/one', 'one'] != ['one', 'sub/sub sub/one']

First differing element 0:
sub/sub sub/one
one

- ['sub/sub sub/one', 'one']
+ ['one', 'sub/sub sub/one']

======================================================================
FAIL: test retrieving the names of bound objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/naming/tests/context_test_case.py", line 514, in test_search
    self.assertEqual( names, ['one', 'sub/sub sub/one'] )
AssertionError: Lists differ: ['sub/sub sub/one', 'one'] != ['one', 'sub/sub sub/one']

First differing element 0:
sub/sub sub/one
one

- ['sub/sub sub/one', 'one']
+ ['one', 'sub/sub sub/one']

======================================================================
FAIL: test retrieving the names of bound objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/naming/tests/context_test_case.py", line 514, in test_search
    self.assertEqual( names, ['one', 'sub/sub sub/one'] )
AssertionError: Lists differ: ['sub/sub sub/one', 'one'] != ['one', 'sub/sub sub/one']

First differing element 0:
sub/sub sub/one
one

- ['sub/sub sub/one', 'one']
+ ['one', 'sub/sub sub/one']

======================================================================
FAIL: Test if we are able to dump the state to a string.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/persistence/tests/test_spickle.py", line 48, in test_dump_state
    self.assertEqual(str, str1)
AssertionError: "ccopy_reg\n_reconstructor\np0\n(ctest_spickle\nFoo\np1\nc__builtin__\nobject\np2\nNtp3\nRp4\n(dp5\nS'a'\np6\n(itest_spickle\nA\np7\n(dp8\nS'array'\np9\ncnumpy.core.multiarray\n_reconstruct\np10\n(cnumpy\nndarray\np11\n(I0\ntp12\nS'b'\np13\ntp14\nRp15\n(I1\n(I5\ntp16\ncnumpy\ndtype\np17\n(S'f8'\np18\nI0\nI1\ntp19\nRp20\n(I3\nS'<'\np21\nNNNI-1\nI-1\nI0\ntp22\nbI00\nS'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\xd0?\\x00\\x00\\x00\\x00\\x00\\x00\\xe0?\\x00\\x00\\x00\\x00\\x00\\x00\\xe8?\\x00\\x00\\x00\\x00\\x00\\x00\\xf0?'\np23\ntp24\nbsg6\nI100\nsg13\nI200\nsbsg13\nctraits.traits\n__newobj__\np25\n(ctest_spickle\nB\np26\ntp27\nRp28\n(dp29\nS'f'\np30\nF2.0\nsS'i'\np31\nI20\nsS'__traits_version__'\np32\nS'4.5.0'\np33\nsbsS'ref'\np34\ng7\nsb." != "ccopy_reg\n_reconstructor\np0\n(ctest_spickle\nFoo\np1\nc__builtin__\nobject\np2\nNtp3\nRp4\n(dp5\nS'a'\np6\n(itest_spickle\nA\np7\n(dp8\nS'array'\np9\ncnumpy.core.multiarray\n_reconstruct\np10\n(cnumpy\nndarray\np11\n(I0\ntp12\nS'b'\np13\ntp14\nRp15\n(I1\n(I5\ntp16\ncnumpy\ndtype\np17\n(S'f8'\np18\nI0\nI1\ntp19\nRp20\n(I3\nS'<'\np21\nNNNI-1\nI-1\nI0\ntp22\nbI00\nS'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\xd0?\\x00\\x00\\x00\\x00\\x00\\x00\\xe0?\\x00\\x00\\x00\\x00\\x00\\x00\\xe8?\\x00\\x00\\x00\\x00\\x00\\x00\\xf0?'\np23\ntp24\nbsg6\nI100\nsg13\nI200\nsbsg13\nctraits.traits\n__newobj__\np25\n(ctest_spickle\nB\np26\ntp27\nRp28\n(dp29\nS'i'\np30\nI20\nsS'f'\np31\nF2.0\nsS'__traits_version__'\np32\nS'4.5.0'\np33\nsbsS'ref'\np34\ng7\nsb."

======================================================================
FAIL: Test if traited classes can be pickled.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 320, in test_pickle_traits
    self.verify(t, state)
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 110, in verify
    self.assertEqual(lst[-1]['type'], 'instance')
AssertionError: 'reference' != 'instance'

======================================================================
FAIL: Test if the state can be saved like the object itself.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 367, in test_state_is_saveable
    self.verify_state(state1, state)
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/persistence/tests/test_state_pickler.py", line 183, in verify_state
    self.assertEqual(state.inst.__metadata__, state1.inst.__metadata__)
AssertionError: {'initargs': (), 'version': [(('A', 'test_state_pickler'), -1)], 'module': 'test [truncated]... != {'initargs': (), 'version': [(('A', 'test_state_pickler'), -1)], 'module': 'test [truncated]...
  {'class_name': 'A',
   'has_instance': True,
-  'id': 5,
?        ^

+  'id': 4,
?        ^

   'initargs': (),
   'module': 'test_state_pickler',
   'type': 'instance',
   'version': [(('A', 'test_state_pickler'), -1)]}

======================================================================
FAIL: preferences node changed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Enthought/ETS/apptools/apptools/preferences/tests/preferences_helper_test_case.py", line 438, in test_preferences_node_changed
    self.assertEqual('width', listener.trait_name)
AssertionError: 'width' != 'bgcolor'
-------------------- >> begin captured logging << --------------------
apptools.preferences.preferences: DEBUG: loading preferences from </Users/mdickinson/Enthought/ETS/apptools/apptools/preferences/tests/example.ini>
apptools.preferences.preferences: DEBUG: loading preferences from </Users/mdickinson/Enthought/ETS/apptools/apptools/preferences/tests/example.ini>
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 380 tests in 1.234s

FAILED (errors=1, failures=9)
```

**Comment by aaronayres35** [comment]
I tried running `PYTHONHASHSEED=random python -m unittest discover -v apptools` several times and none of the tests failed.  Is it safe to say this issue can be closed?

**Comment by mdickinson** [comment]
> Is it safe to say this issue can be closed?

Hmm. *Possibly*.

The `PYTHONHASHSEED=random` failures are *symptoms* of a problem rather than the problem itself. The problem is dependence on dictionary ordering. Even though that ordering is de facto guaranteed in Python 3.6 and actually guaranteed by the language for Python >= 3.7, we may still want to track down and fix these cases. (I'd guess that they still exist with Python 3.5.)

OTOH, that may be just too much effort.

**Comment by mdickinson** [comment]
Okay, I can't reproduce these failures even with Python 3.5. Closing.
